// Generated by CoffeeScript 1.4.0
(function() {
  var isIt;

  isIt = function() {
    var day, now;
    now = moment();
    day = now.day();
    return day === 3 || (now.isoWeek() % 2 === 0 && (day === 5 || day === 6 || day === 0));
  };

  $(function() {
    var buttonPrimary, buttonSuccess, buttonWarning;
    buttonPrimary = $('.btn-primary');
    buttonSuccess = $('.btn-success');
    buttonWarning = $('.btn-warning');
    buttonPrimary.popover({
      placement: 'top',
      html: true,
      trigger: 'manual'
    });
    buttonSuccess.popover({
      placement: 'top',
      html: true,
      trigger: 'manual'
    });
    buttonWarning.popover({
      placement: 'top',
      html: true,
      trigger: 'manual'
    });
    buttonPrimary.click(function() {
      buttonPrimary.attr('data-content', isIt() ? "Du har ret, det er fardag!" : "Ehm, hvad? Nej, det er ikke fardag i dag!");
      return buttonPrimary.popover('toggle');
    });
    buttonSuccess.click(function() {
      buttonSuccess.attr('data-content', isIt() ? "Wtf? Jo, det ER fardag!" : "Du har ret! Det er nemlig IKKE fardag i dag!");
      return buttonSuccess.popover('toggle');
    });
    return buttonWarning.click(function() {
      buttonWarning.attr('data-content', "Ja, du er sgu for dum.<br>Prøv Google!");
      return buttonWarning.popover('toggle');
    });
  });

}).call(this);
